### ISSUE TITLE
Error messages while running multi level (three level meta analysis)

### ISSUE THREAD

**Issue by arinbasu** [mikewlcheung/metasem#6]
Hi Mike,
I tried to replicate the three level multivariate meta-analysis with metaSEM in Rstudio (R version 4.1). I keep getting the following error message:
" Error in if (method != "MH" | method.tau != "DL" | !(sm %in% c("OR", "RR", : argument is of length zero"
I tried looking into the meta3 function, I could not find where this code was written or how to correct it.
For your reference, here is the code I tried to run:

```multi_model = meta3(y = logOR,
                    v = v,
                    cluster = Cluster,
                    data = Bornmann07,
                    model.name = "three level")

summary(multi_model)
```
Can you kindly advise what to do?
Kind regards,
Arindam Basu

**Comment by mikewlcheung** [comment]
Hi Arindam,

metaSEM does not have an error message related to "MH", "DL", "OR", "RR". Did you accidentally confuse it with another package? If not, could you please provide sample data and code to reproduce it?

Mike

**Comment by arinbasu** [comment]
Hi Mike,
Let me reproduce for you what I was trying to do and step by step the error messages.
Just so that this becomes reproducible, I am working in Rstudio.cloud using R version 4.1

```
# load the libraries
library(lme4)
library(metafor)
library(metaSEM)
library(tidyverse)
library(lavaan)
```
I used the world values survey data you wrote in your book on Meta analysis using SEM and tried to run the three level meta analysis model using the following code:

```
head(wvs94a)
wvs1 <- metaSEM::meta(y=cbind(lifesat, lifecon),
            v=cbind(lifesat_var, inter_cov, lifecon_var),
            data=wvs94a)

summary(wvs1)

multi_model = meta3(y = logOR,
                    v = v,
                    cluster = Cluster,
                    data = Bornmann07,
                    model.name = "three level")

summary(multi_model)

```
This produced the following error message:

```
Error in if (method != "MH" | method.tau != "DL" | !(sm %in% c("OR", "RR", : argument is of length zero

```
Traceback:
6. update.meta(x, warn = FALSE)
5. update(x, warn = FALSE)
4. updateversion(object)
3. summary.meta(wvs1)
2. summary(wvs1)
1. summary(wvs1)

Does this help?
I looked up meta3, I could not find any error message related to MH, DL, etc as you have written indeed.
What might have gone wrong?

**Comment by mikewlcheung** [comment]
Hi Arindam,

Thanks for providing more detail. I have tried the code in three different Linux machines; however, they run without any error.

I don't have an answer. But I have several thoughts:

1) It is not a good idea to load many libraries. Some of the functions are likely masked by the later libraries. For example, some users have complained that they cannot use rerun() in the metaSEM package. It turns out that it is masked by purr::rerun(). 

2) Your Traceback is related to the wvs1 object with meta(), which is different from the multi_model object with meta3().

3) After Googling the terms, update.meta(x, warn = FALSE), update(x, warn = FALSE), and updateversion(object) seem to be from the meta package. Would it be possible that you have also loaded it?

https://rdrr.io/cran/meta/src/R/update.meta.R
https://rdrr.io/github/guido-s/meta/src/R/updateversion.R

Mike

**Comment by arinbasu** [comment]
Hi Mike,
Thank you.
This solves the problem.
Yes, I think if I only use 
`library(metaSEM)`
and run the example, it runs fine.
It seems `meta` or `metafor` may interfere with the namespace related conflicts.

**Comment by arinbasu** [comment]
I think with this, I request to close this issue.
